### PR TITLE
Remove dependency on rimraf

### PR DESCRIPTION
**Pull request by stianjensen**
fs-extra was basically created to avoid having to install both mkdirp, rimraf etc, and is also already installed here, so we can avoid using both at the same time.

This moves rimraf to devDependencies, since it's still conveniant for the local 'clean' and 'prepack' commands.

At the same time, update to fs-extra 10.x, since it's lowest supported node version there is now still lower than the lowest supported version for patch-package, but has still introduced the option of using node's native fs.rm when available:
https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md

(fs-extra 11.x only works on node 14.14+, while patch-package currently supports all 14.x versions)

### CODE REVIEW

**Comment by ZuBB** [comment]
just wanna add that rimraf throws a warn

> npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported

**Review by GSS-Rishi — APPROVED** [review]

**Comment by bombillazo** [comment]
Is this project still supported?

**Comment by orta** [comment]
Looks like fs-extra's `removeSync` [is recursive](https://github.com/jprichardson/node-fs-extra/blob/master/docs/remove-sync.md), so this should be the same 👍🏻

**Comment by rakleed** [comment]
@orta could you please publish a new version with these changes?

**Comment by niksy** [comment]
Are there any blockers for getting this released? The only one I could think of is this:

```
fs-extra 11.x only works on node 14.14+, while patch-package currently supports all 14.x versions
```

/cc @orta

**Comment by Kamahl19** [comment]
@orta  could you please make a release? Thanks!

**Pull request merged**
