### PR TITLE
"--retry-on-clean" flag for re-applying patch if it could not be applied

### PR DESCRIPTION
**Pull request by altaibayar**
If you are delivering your work continuously as a patch into an existing package then after applying `patch1` and trying to apply `patch2` patch-package fails (screenshot1).

`--retry-on-clean` flag tells patch-package if patch and package version are same but patch could not be applied then the flag tells patch-package to reapply patch again but on top of freshly installed dependency from NPM.

screenshot1 - previous state when patch-package failed
screenshot2 - if patch was applied without any problem
screenshot3 - if `--retry-on-clean` flag is present

screenshot1
previous

screenshot2
success1

screenshot3
success2

### CODE REVIEW

**Comment by ds300** [comment]
Thanks for the idea. The error message already says 'try removing node_modules and trying again' which I think covers this situation right? I think the only benefit of having a special flag in patch-package is to save time by not reinstalling node_modules?

**Comment by altaibayar** [comment]
> Thanks for the idea. The error message already says 'try removing node_modules and trying again' which I think covers this situation right? I think the only benefit of having a special flag in patch-package is to save time by not reinstalling node_modules?

@ds300  Yes. it is to make workflow without unnecessary bumps

**Comment by MartinSherburn** [comment]
This is important for large teams working on a shared codebase, it avoids each individual person who is working on the codebase having to read and understand what went wrong, manually delete node_modules and try again. It may only take 5 minutes to resolve it but if there are say 100 people who each need to do this it adds up to 500 minutes (~ 8 hours) of wasted time. With this flag the whole process can be automated.

**Comment by ds300** [comment]
Thanks for the contribution but I'm gonna pass. This issue is a very niche edge case as far as I can tell.

I also added a new flag today, `--error-on-fail`, so that you can achieve the same effect using a simple bash wrapper. 

```sh
# yarn postinstall script
if ! yarn patch-package --error-on-fail && [ "$IS_RETRYING" != "yes" ];
then
  echo "removing node_modules and trying again"
  rm -rf node_modules
  IS_RETRYING=yes yarn install
fi
```

**Pull request closed without merging**
