### PR TITLE
make work with pnpm

### PR DESCRIPTION
**Pull request by milahu**

### CODE REVIEW

**Comment by idkjs** [comment]
Any plans to merge this?

**Review by niieani — APPROVED** [review]

**Comment by biowaffeln** [comment]
@idkjs  in the meantime you could use `patch-package` to patch `patch-package`.

**Comment by niieani** [comment]
@biowaffeln unfortunately that doesn't work. `patch-package` crashes before it gets a chance to patch itself 🤷

**Comment by emanueleDiVizio** [comment]
I see this has been approved, is there any roadmap to release this on npm?

**Comment by niieani** [comment]
@emanueleDiVizio I'm not a maintainer, so my approval doesn't really mean anything :) But I did review the change and it seems legit 👍.

**Comment by ds300** [comment]
Thanks for this! 🙏🏼  Sorry it took me so long to get around to merging.

**Comment by ds300** [comment]
This was just released in v6.4.3

**Comment by milahu** [comment]
> Sorry it took me so long to get around to merging.

190 days for 3 lines of code : D \*scnr\*

**Pull request merged**
