### PR TITLE
[Feat] Add --create-issue character limit check

### PR DESCRIPTION
**Pull request by bombillazo**
Fixes https://github.com/ds300/patch-package/issues/328

This change adds a limit to the message sent to the GitHub create issue URL to avoid URL too long errors.

If the diff contents exceed 300 characters (this was chosen arbitrarily), the diff contents are replaced with a comment message replacement, and the console outputs the complete PR diff contents and instructs the user to copy/paste the diff into the PR description manually.

(The old PR was closed automatically when I merged the OG repo into the forked repo)

### CODE REVIEW

**Comment by bombillazo** [comment]
Hey @ds300 , a PR review would be appreciated :)

**Comment by bombillazo** [comment]
Hey @ds300 , are there any other maintainers that could take a look? Communication see,s like it was suddenly cut off, are you still present?

**Comment by bombillazo** [comment]
Hey, long time no talk, any update here?

**Comment by bombillazo** [comment]
@ds300 Hey so im cleaning my PRs I'm contributing around, any chance this can be reviewed again/merged to incorporate this feature in a new release? There hasn't been any new releases in a year

**Comment by bombillazo** [comment]
hey @orta any chance of reviewing this PR?

**Comment by orta** [comment]
I think this is a good idea, lets have it in

**Comment by bombillazo** [comment]
Thanks so much @orta!

**Pull request merged**
