### PR TITLE
Support for canary versions from lerna

### PR DESCRIPTION
**Pull request by snowystinger**
Support for canary versions from lerna https://github.com/ds300/patch-package/issues/212

I need some help with the test, I don't know how to generate the snapshot

### CODE REVIEW

**Comment by snowystinger** [comment]
hello?

**Comment by mikehardy** [comment]
I'm working on a github workflow that will auto-generate patch-package patch artifacts for PRs, and it would be nice to support appending the PR commit SHA to the patch files in order to have them named unambiguously (along with the PR as a pre-release tag, actually) so I'd love this to be integrated.

Instead of having this patch on PR1234, SHA a5a7d6a5:

`patches/@react-native-firebase+database@6.7.2.txt`

I could have:

`patches/@react-native-firebase+database@6.7.2-PR1234+a5a7d6a5.txt`

Then it would be very easy to see exactly where the patch came from

**Comment by ds300** [comment]
Thanks @snowystinger this change makes sense :+1: Sorry it took me so long to get around to it.

I'm going to merge and then fix up the tests directly on master 🙏🏼

**Comment by ds300** [comment]
fixup commit incase anybody is interested: https://github.com/ds300/patch-package/commit/2f1c855631decd5662b46f32b21ba3e54ecb5103

**Comment by mikehardy** [comment]
Hey @ds300 just wanted to say this package is a huge part of my react-native existence haha - thanks for the package in general, and the current time here merging this :-). Cheers

**Comment by ds300** [comment]
This was just released in [v6.3.0](https://github.com/ds300/patch-package/releases/tag/v6.3.0)

**Pull request merged**
