### PR TITLE
Align tslint and prettier config, and use default prettier settings

### PR DESCRIPTION
**Pull request by KevinVlaanderen**
I'm not sure if you're open to such a style-related MR, but it seemed to me that there were too many customizations, and potential mismatches between TSlint and prettier.
I've kept some custom tslint rules to prevent having to make too many code changes.
All changes are style-related.

### CODE REVIEW

**Comment by ds300** [comment]
Hi! :wave:

I find semicolons offer no value, and in fact I think they get in the way sometimes while I'm using prettier. Similarly, I find that putting trailing commas everywhere is really nice for keeping commit diffs minimal and preventing syntax errors while editing code.

I appreciate that not everybody shares those opinions. What's your thinking behind your style choices?

**Comment by KevinVlaanderen** [comment]
These things really are just a matter of taste, of course.
My main reasoning in this case is to use defaults as much as possible. As this is an open source project, defaults provide a nice baseline that you can use to avoid such discussions about commas, semis, newlines, spaces.

**Comment by ds300** [comment]
I'm going to close this. Defaults are normally useful guides, but in prettier's case I think they were antiquated from the beginning. Especially with respect to trailing commas, which are quite valuable and have no downsides now that they are supported everywhere.

**Comment by KevinVlaanderen** [comment]
Alright. No problem.

**Pull request closed without merging**
