### PR TITLE
Bump fs-extra to 9.x

### PR DESCRIPTION
**Pull request by stianjensen**
This gets in some performance improvements, as well as upgrades underlying dependencies to newer versions.

Bumping to 9.x will require nodejs 10.x as a minimum version, which is
already the minimum version declared in package.json.

https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by orta** [comment]
Yeah, doing a lower version is better IMO - this isn't a good enough reason to force a semver major on everyone using patch-package

**Comment by stianjensen** [comment]
Changed to update to 9.x

**Comment by orta** [comment]
Looks good to me, thanks!

**Comment by ds300** [comment]
Released in [v6.5.1](https://github.com/ds300/patch-package/releases/tag/v6.5.1), thanks for the contribution 🎉 ❤️

**Pull request merged**
