### PR TITLE
Add --error-on-warn flag to exit 1 on warnings

### PR DESCRIPTION
**Pull request by mvargeson**
This addresses the scenario described in #314. I'm not sure if this is a desirable addition to the project but we are running into issues with automated dependency updates not taking into consideration patched dependencies and would like to prevent these warnings from making it onto our main branch.

The change is pretty minimal and follows the pattern that the `--error-on-fail` flag took. This changes the `process.exit` logic at the end of `applyPatchesForApp` and gives that function a new parameter, `shouldExitWithWarning` that looks at the flag boolean value. There are a couple of questions that I have:
1. Does `shouldExitWithWarning` make sense? I may be misunderstanding terminology in variable names so please feel free to suggest something better.
2. Do I need to consider environmental variables similar to `--error-on-fail`? I did not fully understand if that would be a good idea here.
3. Would it be better to try to introduce a single flag that would take both warning and failures levels into account before deciding the exit code? Again, I mostly tried to just stick with the change that was the least amount of change but open to something else here.

Feel free to close out if not interested in this addition or request changes if this doesn't seem like the correct implementation.

### CODE REVIEW

**Comment by jraoult** [comment]
I would love to see it landing 👏. @ds300 any chance you would consider this?

**Comment by mvargeson** [comment]
There have been no updates to this repository in over a here; closing this out. Feel free to reopen if the project is revived at any point.

**Comment by orta** [comment]
I think this PR as-is is reasonable, I can see the idea of switching to a `--fail-on=warn` or `--fail-on=error` but I don't think it's compelling enough to warrant breaking existing flows, doing server bumps etc. So, lets have this in 👍🏻

**Comment by jraoult** [comment]
Oh my 🎉 I'm sadly not using `patch-package` anymore, but my 2021 self is thanking you. It probably means the original issue can be closed as solved as well @orta (cf. https://github.com/ds300/patch-package/issues/314)

**Pull request merged**
