### PR TITLE
Support sub module discovery

### PR DESCRIPTION
**Pull request by mbenzenhoefer**
This pull requests enables the patching of submodules in your node_modules.

Example: `node_modules/@x/y/node_moduels/@abc/def`

The file structure in patches folder has to be the following:
`@x/y/node_moduels/@abc/def+1.0.0.patch`

Note: tests on my local Mac failed as mentioned in issue#66, hope all works fine with CI server.

### CODE REVIEW

**Comment by ds300** [comment]
Thanks! This is a good idea. :+1: I'm going to simplify the implementation and add tests before merging.

**Comment by ds300** [comment]
Did I say 'simplify'? I meant 'massively complexify' 😬 

I did a few things extra here:

1. Improve patch creation performance by only installing the package to be patched
2. Make it so you don't need to write intermediate `node_modules` folders when you patch a nested package. e.g. `npx patch-package foo/bar` instead of `npx patch-package foo/node_modules/bar`. and `npx patch-package @steve/foo/@alice/bar` instead of `npx patch-package @steve/foo/node_modules/@alice/bar`
3. Flatten the `/patches` directory.
4. Upgrade prettier and typescript.
5. Refactor and improve generative tests
6. Improve some error messages

**Comment by ds300** [comment]
Thanks again! :tada: :heart:

**Comment by mbenzenhoefer** [comment]
Thanks! When are you going to release the new version so I can check whether all in my project is still running fine? :)

**Comment by ds300** [comment]
It's released in `patch-package@beta`. You might need to re-create your patch file.

**Pull request merged**
