### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by TheMonolithX64**
Update rifraf package to 5.0.5

- Update `rifraf` to consume `glob` 9+ which removes the [vulnerable version using unmaintained `inflight`dependency](https://github.com/isaacs/inflight/issues/5)

### CODE REVIEW

**Comment by joaoaccaldeira** [comment]
+1 for this!

@ds300 would you have a look at it and consider releasing a version after this security vulnerability fix?

**Comment by ZuBB** [comment]
There is another PR that deals with this issue in a better way (imo): https://github.com/ds300/patch-package/pull/517

**Comment by anasvemmully** [comment]
any update on this issue!

**Comment by orta** [comment]
https://github.com/ds300/patch-package/pull/517 handled the same thing 👍🏻

**Pull request closed without merging**
