### PR TITLE
fix: change no patch files found error from red to bright blue

### PR DESCRIPTION
**Pull request by dmhalejr**
PR Contains:
- Changing "No Patch Files Found" error to fire from **red** to **bright blue**

Possible close for #145

### CODE REVIEW

**Comment by dmhalejr** [comment]
The error from the TravisCI build is regarding a `yarn install` that may have been updated. 
```
yarn install v1.22.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error np@6.2.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
warning np@6.2.0: The engine "git" appears to be invalid.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by ds300** [comment]
Thanks! Sorry it took me a long time to get to this.

**Comment by dmhalejr** [comment]
It's all good man! 👍 Thanks!

**Comment by ds300** [comment]
This was just released in [v6.3.0](https://github.com/ds300/patch-package/releases/tag/v6.3.0)

**Pull request merged**
